# Generated by Django 3.1.6 on 2021-02-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='c_id',
            new_name='course',
        ),
    ]
