# Generated by Django 3.1.6 on 2021-02-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210222_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='uploaded_by',
        ),
    ]
